<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Images\adamandeve1.jpg" />
		<None Remove="Images\apples.png" />
		<None Remove="Images\cupids.jpg" />
		<None Remove="Images\defaultprofile.png" />
		<None Remove="Images\glassbg.jpg" />
		<None Remove="Images\moreangelbg.jpg" />
		<None Remove="Images\paintingbg.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="DatesApi">
	    <HintPath>..\..\datingappmodel1\interfaceapi\bin\Debug\net8.0\DatesApi.dll</HintPath>
	  </Reference>
	  <Reference Include="ModelDates">
	    <HintPath>..\..\datingappmodel1\ModelDates\bin\Debug\net8.0\ModelDates.dll</HintPath>
	  </Reference>
	  <Reference Include="ViewModel">
	    <HintPath>..\..\datingappmodel1\interfaceapi\bin\Debug\net8.0\ViewModel.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Images\adamandeve1.jpg" />
		<Resource Include="Images\apples.png" />
		<Resource Include="Images\cupids.jpg" />
		<Resource Include="Images\defaultprofile.png" />
		<Resource Include="Images\glassbg.jpg" />
		<Resource Include="Images\moreangelbg.jpg" />
		<Resource Include="Images\paintingbg.jpg" />
	</ItemGroup>

</Project>